// using this idl we gen the stubs for serializing, deserizling and also for server client gen code

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: audio_streaming.proto

package audiostreaming

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// type of the audio chunks
type AudioChunks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawAudioChunk []byte                 `protobuf:"bytes,1,opt,name=rawAudioChunk,proto3" json:"rawAudioChunk,omitempty"`
	ChunkId       int32                  `protobuf:"varint,2,opt,name=chunkId,proto3" json:"chunkId,omitempty"`
	// metadata fields — only set in first chunk when is_metadata=true
	IsMetadata    bool  `protobuf:"varint,3,opt,name=is_metadata,json=isMetadata,proto3" json:"is_metadata,omitempty"`
	Age           int32 `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Sex           int32 `protobuf:"varint,5,opt,name=sex,proto3" json:"sex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunks) Reset() {
	*x = AudioChunks{}
	mi := &file_audio_streaming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunks) ProtoMessage() {}

func (x *AudioChunks) ProtoReflect() protoreflect.Message {
	mi := &file_audio_streaming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunks.ProtoReflect.Descriptor instead.
func (*AudioChunks) Descriptor() ([]byte, []int) {
	return file_audio_streaming_proto_rawDescGZIP(), []int{0}
}

func (x *AudioChunks) GetRawAudioChunk() []byte {
	if x != nil {
		return x.RawAudioChunk
	}
	return nil
}

func (x *AudioChunks) GetChunkId() int32 {
	if x != nil {
		return x.ChunkId
	}
	return 0
}

func (x *AudioChunks) GetIsMetadata() bool {
	if x != nil {
		return x.IsMetadata
	}
	return false
}

func (x *AudioChunks) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *AudioChunks) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

// type of the parkinsonsdetectionresult
type ParkinsonsDetectionResult struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	IsHavingParkinsons     bool                   `protobuf:"varint,1,opt,name=isHavingParkinsons,proto3" json:"isHavingParkinsons,omitempty"`
	Severity               float32                `protobuf:"fixed32,2,opt,name=severity,proto3" json:"severity,omitempty"`
	Suggestion             string                 `protobuf:"bytes,3,opt,name=suggestion,proto3" json:"suggestion,omitempty"`
	ExtractedVoiceFeatures *structpb.Struct       `protobuf:"bytes,4,opt,name=extracted_voice_features,json=extractedVoiceFeatures,proto3" json:"extracted_voice_features,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ParkinsonsDetectionResult) Reset() {
	*x = ParkinsonsDetectionResult{}
	mi := &file_audio_streaming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParkinsonsDetectionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParkinsonsDetectionResult) ProtoMessage() {}

func (x *ParkinsonsDetectionResult) ProtoReflect() protoreflect.Message {
	mi := &file_audio_streaming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParkinsonsDetectionResult.ProtoReflect.Descriptor instead.
func (*ParkinsonsDetectionResult) Descriptor() ([]byte, []int) {
	return file_audio_streaming_proto_rawDescGZIP(), []int{1}
}

func (x *ParkinsonsDetectionResult) GetIsHavingParkinsons() bool {
	if x != nil {
		return x.IsHavingParkinsons
	}
	return false
}

func (x *ParkinsonsDetectionResult) GetSeverity() float32 {
	if x != nil {
		return x.Severity
	}
	return 0
}

func (x *ParkinsonsDetectionResult) GetSuggestion() string {
	if x != nil {
		return x.Suggestion
	}
	return ""
}

func (x *ParkinsonsDetectionResult) GetExtractedVoiceFeatures() *structpb.Struct {
	if x != nil {
		return x.ExtractedVoiceFeatures
	}
	return nil
}

var File_audio_streaming_proto protoreflect.FileDescriptor

const file_audio_streaming_proto_rawDesc = "" +
	"\n" +
	"\x15audio_streaming.proto\x12\x0eaudiostreaming\x1a\x1cgoogle/protobuf/struct.proto\"\x92\x01\n" +
	"\vAudioChunks\x12$\n" +
	"\rrawAudioChunk\x18\x01 \x01(\fR\rrawAudioChunk\x12\x18\n" +
	"\achunkId\x18\x02 \x01(\x05R\achunkId\x12\x1f\n" +
	"\vis_metadata\x18\x03 \x01(\bR\n" +
	"isMetadata\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\x12\x10\n" +
	"\x03sex\x18\x05 \x01(\x05R\x03sex\"\xda\x01\n" +
	"\x19ParkinsonsDetectionResult\x12.\n" +
	"\x12isHavingParkinsons\x18\x01 \x01(\bR\x12isHavingParkinsons\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\x02R\bseverity\x12\x1e\n" +
	"\n" +
	"suggestion\x18\x03 \x01(\tR\n" +
	"suggestion\x12Q\n" +
	"\x18extracted_voice_features\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x16extractedVoiceFeatures2w\n" +
	"\x0eAudioStreaming\x12e\n" +
	"\x19DetectParkinsonsFromAudio\x12\x1b.audiostreaming.AudioChunks\x1a).audiostreaming.ParkinsonsDetectionResult(\x01BEZCgithub.com/yeswanth08/go-parkinsons-server/gen-stubs;audiostreamingb\x06proto3"

var (
	file_audio_streaming_proto_rawDescOnce sync.Once
	file_audio_streaming_proto_rawDescData []byte
)

func file_audio_streaming_proto_rawDescGZIP() []byte {
	file_audio_streaming_proto_rawDescOnce.Do(func() {
		file_audio_streaming_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_audio_streaming_proto_rawDesc), len(file_audio_streaming_proto_rawDesc)))
	})
	return file_audio_streaming_proto_rawDescData
}

var file_audio_streaming_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_audio_streaming_proto_goTypes = []any{
	(*AudioChunks)(nil),               // 0: audiostreaming.AudioChunks
	(*ParkinsonsDetectionResult)(nil), // 1: audiostreaming.ParkinsonsDetectionResult
	(*structpb.Struct)(nil),           // 2: google.protobuf.Struct
}
var file_audio_streaming_proto_depIdxs = []int32{
	2, // 0: audiostreaming.ParkinsonsDetectionResult.extracted_voice_features:type_name -> google.protobuf.Struct
	0, // 1: audiostreaming.AudioStreaming.DetectParkinsonsFromAudio:input_type -> audiostreaming.AudioChunks
	1, // 2: audiostreaming.AudioStreaming.DetectParkinsonsFromAudio:output_type -> audiostreaming.ParkinsonsDetectionResult
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_audio_streaming_proto_init() }
func file_audio_streaming_proto_init() {
	if File_audio_streaming_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_audio_streaming_proto_rawDesc), len(file_audio_streaming_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_audio_streaming_proto_goTypes,
		DependencyIndexes: file_audio_streaming_proto_depIdxs,
		MessageInfos:      file_audio_streaming_proto_msgTypes,
	}.Build()
	File_audio_streaming_proto = out.File
	file_audio_streaming_proto_goTypes = nil
	file_audio_streaming_proto_depIdxs = nil
}
