// using this idl we gen the stubs for serializing, deserizling and also for server client gen code

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.1
// source: audio_streaming.proto

package audiostreaming

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AudioStreaming_DetectParkinsonsFromAudio_FullMethodName = "/audiostreaming.AudioStreaming/DetectParkinsonsFromAudio"
)

// AudioStreamingClient is the client API for AudioStreaming service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AudioStreamingClient interface {
	// rpc methods using for this server client interaction
	DetectParkinsonsFromAudio(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AudioChunks, ParkinsonsDetectionResult], error)
}

type audioStreamingClient struct {
	cc grpc.ClientConnInterface
}

func NewAudioStreamingClient(cc grpc.ClientConnInterface) AudioStreamingClient {
	return &audioStreamingClient{cc}
}

func (c *audioStreamingClient) DetectParkinsonsFromAudio(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AudioChunks, ParkinsonsDetectionResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AudioStreaming_ServiceDesc.Streams[0], AudioStreaming_DetectParkinsonsFromAudio_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AudioChunks, ParkinsonsDetectionResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AudioStreaming_DetectParkinsonsFromAudioClient = grpc.ClientStreamingClient[AudioChunks, ParkinsonsDetectionResult]

// AudioStreamingServer is the server API for AudioStreaming service.
// All implementations must embed UnimplementedAudioStreamingServer
// for forward compatibility.
type AudioStreamingServer interface {
	// rpc methods using for this server client interaction
	DetectParkinsonsFromAudio(grpc.ClientStreamingServer[AudioChunks, ParkinsonsDetectionResult]) error
	mustEmbedUnimplementedAudioStreamingServer()
}

// UnimplementedAudioStreamingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAudioStreamingServer struct{}

func (UnimplementedAudioStreamingServer) DetectParkinsonsFromAudio(grpc.ClientStreamingServer[AudioChunks, ParkinsonsDetectionResult]) error {
	return status.Error(codes.Unimplemented, "method DetectParkinsonsFromAudio not implemented")
}
func (UnimplementedAudioStreamingServer) mustEmbedUnimplementedAudioStreamingServer() {}
func (UnimplementedAudioStreamingServer) testEmbeddedByValue()                        {}

// UnsafeAudioStreamingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AudioStreamingServer will
// result in compilation errors.
type UnsafeAudioStreamingServer interface {
	mustEmbedUnimplementedAudioStreamingServer()
}

func RegisterAudioStreamingServer(s grpc.ServiceRegistrar, srv AudioStreamingServer) {
	// If the following call panics, it indicates UnimplementedAudioStreamingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AudioStreaming_ServiceDesc, srv)
}

func _AudioStreaming_DetectParkinsonsFromAudio_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AudioStreamingServer).DetectParkinsonsFromAudio(&grpc.GenericServerStream[AudioChunks, ParkinsonsDetectionResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AudioStreaming_DetectParkinsonsFromAudioServer = grpc.ClientStreamingServer[AudioChunks, ParkinsonsDetectionResult]

// AudioStreaming_ServiceDesc is the grpc.ServiceDesc for AudioStreaming service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AudioStreaming_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "audiostreaming.AudioStreaming",
	HandlerType: (*AudioStreamingServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DetectParkinsonsFromAudio",
			Handler:       _AudioStreaming_DetectParkinsonsFromAudio_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "audio_streaming.proto",
}
