# using phony for exporting and importing the cmds
.PHONY: install_tools

install_tools:
	go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
	go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest