name: publish parkinsons sdk

on:
  push:
    branchs:
      - main
    paths:
      - 'open-api/openapi.yaml' 

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@yeswanth08'

      - name: Install openapi-typescript-codegen
        run: npm install -g openapi-typescript-codegen

      - name: Generate SDK
        run: make gen_sdk

      - name: Install & Build
        run: cd sdk && npm install && npx tsc --declaration --emitDeclarationOnly || true

      - name: Publish
        run: cd sdk && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GO_SERVER_PAT }}
